### PR TITLE
Fixing incorrect URI

### PR DESCRIPTION
**Pull request by m-moris**
Deployment was failed from azure portal, because URI is incorrect.

### CODE REVIEW

**Comment by chagarw** [comment]
The issue was because resource group name had few upper case letters and the template uses it for dns prefix. I have corrected the issue. Please try now.

**Comment by m-moris** [comment]
I got following error in azure portal. The URI is not found.

> // Error loading template from https://raw.githubusercontent.com/chagarw/MDPP/master/101-vm-simple-windows-md/azuredeploy.json

I think correct URI is https://raw.githubusercontent.com/chagarw/MDPP/master/101-vm-simple-windows-md-os-data/azuredeploy.json

Thanks.

**Comment by chagarw** [comment]
Yes, the correct URI is https://raw.githubusercontent.com/chagarw/MDPP/master/101-vm-simple-windows-md-os-data/azuredeploy.json

Please, let me know how the steps which led you to the above error. Thanks.

**Comment by m-moris** [comment]
I just tried to click "Deploy Azure" Button in https://github.com/chagarw/MDPP/tree/master/101-vm-simple-windows-md-os-data

As you know, if this button clicked, the arm template of the URI use to deploy via azure portal.
1. Click "Deploy to Azure" button.
   image
2. Jump to azure portal automatically and, error was occurred.
   image
3. Click edit template button.

image

Error message.

> // Error loading template from https://raw.githubusercontent.com/chagarw/MDPP/master/101-vm-simple-windows-md/azuredeploy.json

**Comment by chagarw** [comment]
Thanks for pointing this issue. I have fixed this. Please check and confirm.

**Comment by m-moris** [comment]
Thanks a lot. It works fine and Close this issue.

**Pull request closed without merging**
